input_line_1 = int(input())
input_line_2 = int(input())
input_line_3 = int(input())
input_line_4 = int(input())
input_line_5 = int(input())
print(min([input_line_1, input_line_2, input_line_3, input_line_4, input_line_5])
)
